Add pattern: Services - Three Columns
WordPress/twentytwentyfive pull request #114
Opened 2024-08-23 13:31 UTC by huzaifaalmesbah

Fixes #80

2024-08-23 14:22 UTC, juanfra reviewed
Thanks for the PR @huzaifaalmesbah!

I left a few comments on the code, to improve some things. I'd like to ask is if we can work on the indentation of the code. And also, if we can include artifacts when we're adding PRs that include changes that are visual (screenshot or screencast will work). Thanks 🙌

2024-08-23 14:22 UTC, juanfra commented on patterns/services-three-columns.php
> +<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"right":"var:preset|spacing|50","left":"var:preset|spacing|50","top":"var:preset|spacing|50","bottom":"var:preset|spacing|50"},"blockGap":
I believe we can avoid using the background color when it's base.

2024-08-23 14:22 UTC, juanfra commented on patterns/services-three-columns.php
> +<figure class="wp-block-image size-full"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images//image-from-rawpixel-id-2222755.webp" alt="" style="aspect-ratio:4/3;object-fit
There's a double slash in the image URL.

```suggestion
<figure class="wp-block-image size-full"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/image-from-rawpixel-id-2222755.webp" alt="" style="aspect-ratio:4/3;object-fit:cover"/></figure>
```

2024-08-23 14:22 UTC, juanfra commented on patterns/services-three-columns.php
> +<figure class="wp-block-image size-full is-style-default"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images//image-from-rawpixel-id-2224378.webp" alt="" style="aspect-rat
There's a double slash in the image URL.
```suggestion
<figure class="wp-block-image size-full is-style-default"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/image-from-rawpixel-id-2224378.webp" alt="" style="aspect-ratio:4/3;object-fit:cover"/></figure>
```

2024-08-23 14:22 UTC, juanfra commented on patterns/services-three-columns.php
> +<figure class="wp-block-image size-full"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images//image-from-rawpixel-id-2211732.webp" alt="" style="aspect-ratio:4/3;object-fit
There's a double slash in the image URL.
```suggestion
<figure class="wp-block-image size-full"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/image-from-rawpixel-id-2211732.webp" alt="" style="aspect-ratio:4/3;object-fit:cover"/></figure>
```

2024-08-23 14:45 UTC, huzaifaalmesbah commented
Thank you for reviewing, @juanfra. I made the changes according to your suggestion.

2024-08-25 13:50 UTC, shail-mehta commented on patterns/services-three-columns.php
> +<figure class="wp-block-image size-full"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/image-from-rawpixel-id-2222755.webp" alt="" style="aspect-ratio:4/3;object-fit:
@huzaifaalmesbah The alt tags are missing for the images. Could you please add them to all three images?

2024-08-25 13:53 UTC, shail-mehta commented
Alt tags are missing for the images. Could you please add them to all three images in Line no 23,37 & 51

2024-08-27 12:11 UTC, rejaulalomkhan commented
Thanks for the PR @huzaifaalmesbah 
It worked excellently in my tests.

2024-08-27 13:06 UTC, juanfra requested changes
Thanks for working on this @huzaifaalmesbah 

It looks like we need to do a few adjustments to the layout. And also add the `alt` to the images. Please check the following screencast

https://github.com/user-attachments/assets/3848a576-f180-440c-9a30-b2e0306e2d5b

2024-08-27 13:06 UTC, juanfra commented on patterns/services-three-columns.php
> +<figure class="wp-block-image size-full"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/image-from-rawpixel-id-2222755.webp" alt="" style="aspect-ratio:4/3;object-fit:
```suggestion
<figure class="wp-block-image size-full"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/image-from-rawpixel-id-2222755.webp" alt="Image for service" style="aspect-ratio:4/3;object-fit:cover"/></figure>
```

2024-08-27 13:06 UTC, juanfra commented on patterns/services-three-columns.php
> +<figure class="wp-block-image size-full is-style-default"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/image-from-rawpixel-id-2224378.webp" alt="" style="aspect-rati
```suggestion
<figure class="wp-block-image size-full is-style-default"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/image-from-rawpixel-id-2224378.webp" alt="Image for service" style="aspect-ratio:4/3;object-fit:cover"/></figure>
```

2024-08-27 13:06 UTC, juanfra commented on patterns/services-three-columns.php
> +<figure class="wp-block-image size-full"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/image-from-rawpixel-id-2211732.webp" alt="" style="aspect-ratio:4/3;object-fit:
```suggestion
<figure class="wp-block-image size-full"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/image-from-rawpixel-id-2211732.webp" alt="Image for service" style="aspect-ratio:4/3;object-fit:cover"/></figure>
```

2024-08-27 13:06 UTC, juanfra commented on patterns/services-three-columns.php
> +
Let's remove this empty line.

2024-08-27 19:06 UTC, huzaifaalmesbah commented
Hello @juanfra, 
Thank you for your review and suggestions. I’ve implemented the changes based on your feedback. Could you please review my updated PR?

Thanks!

2024-08-28 07:25 UTC, juanfra requested changes
Thank you for working on this @huzaifaalmesbah 

I still see that the layout needs to respect the width of the designs.

https://github.com/user-attachments/assets/97a1c604-bbfe-486b-8f57-f6866f2ce80c

On [this comment](https://github.com/WordPress/twentytwentyfive/pull/114#pullrequestreview-2263294600), I showed a way you could potentially fix it. I also see that the code needs indentation.

Can you please work on these things? Thanks in advance.

2024-08-28 12:56 UTC, huzaifaalmesbah commented
https://github.com/user-attachments/assets/0537eaac-e336-448f-8ab6-befcc1821b14

2024-08-28 14:07 UTC, juanfra requested changes
Thanks for the changes @huzaifaalmesbah 

The layout looks good now. Can you please work on the indentation? Once that's fixed this one should be good to go.

2024-08-28 16:37 UTC, juanfra approved these changes
Thank you very much @huzaifaalmesbah 🏅

2024-08-28 16:38 UTC, merged