update: added comments pattern to required post templates
WordPress/twentytwentyfive pull request #257
Opened 2024-09-08 17:11 UTC by up1512001

**Description**
-added the `` pattern to the News blog single post with sidebar, Photo blog single post.,Text-only blog single post and Right-aligned single post.

fixes https://github.com/WordPress/twentytwentyfive/issues/245

2024-09-08 17:12 UTC, up1512001 commented
@juanfra can you please review this PR?

2024-09-10 08:05 UTC, carolinan commented
Hi
The patterns are not being added because there are typos. There is an extra `:` after `slug`. `<!-- wp:pattern {"slug:":"twentytwentyfive/comments"} /-->`

Is there a reason why the comments are placed outside the `<main>`?

2024-09-10 08:12 UTC, up1512001 commented
@carolinan I have fixed the slug issue. Sorry for not seeing it 🙇. Also, for the blog template, I added it inside the `main` section.

2024-09-10 08:43 UTC, juanfra reviewed
Hi @up1512001 - Thank you for working on this.

For each template, the comments section needs to be located where it was placed in the design. You can check where it is for each template, in the[ Figma file](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3086-124&t=K469cTL478GUFwNB-1). Right now, I am not seeing that the comments are placed in the right locations.

https://github.com/user-attachments/assets/b08a2c46-5b60-4b0b-a46b-65a6ca05142e

2024-09-10 17:11 UTC, carolinan commented
Hi @up1512001 and @eirichmond
There are two open pull requests for this issue now. Both pull requests needs to be updated before they can be merged;
To be mindful of everyone's time, is there anyway you can collaborate on one single PR?

2024-09-10 20:03 UTC, eirichmond commented
Oops! Sorry, I thought @juanfra had assigned it to me, happy to close my PR and continue with this one if that helps @up1512001 ?

2024-09-11 18:22 UTC, up1512001 commented
@juanfra I have fixed the comment pattern placement issue, can you please check now?

2024-09-11 18:24 UTC, up1512001 commented
@eirichmond Thanks! I will add you as a co-author so that you will also receive credits 🙇

2024-09-12 11:05 UTC, juanfra commented
@up1512001 @eirichmond thank you! 

Can you please fix the merge conflicts so that I can take another look at this? Thanks

2024-09-13 17:21 UTC, up1512001 commented
@juanfra resolved merge conflicts.

2024-09-14 06:13 UTC, carolinan commented
@up1512001 Since trunk is being updated frequently, there is another merge conflict now.

2024-09-16 06:12 UTC, carolinan commented
### News blog single post
The comments area is not in the correct position. It needs to be more to the left, aligned with the content above it.

| Figma    | The pull request |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/f5196724-f1e6-4fec-b815-2b78c96e9e6c)  | ![news-single-comment](https://github.com/user-attachments/assets/972d1aa4-58ac-487b-88ae-9db325c261aa) |

2024-09-16 06:22 UTC, carolinan commented
- [x] Photo blog single post -Looks correct to me.

2024-09-16 06:31 UTC, carolinan commented
### Text-aligned single post
The space between the post navigation and the comments area is too large.
The top margin that is added to the comments is combined with the bottom margin on the group above it.
If you move the comments inside that group, it will match the design better: But you also need to adjust the bottom margin on the comments so that the space between the footer and comments is correct.

2024-09-16 06:31 UTC, up1512001 commented
@carolinan fixed `News blog single post` template alignment issue.

2024-09-16 06:38 UTC, carolinan commented
### Right-aligned single post
The comments needs to align with the content, the comments are is too far to the right.
The vertical spacing seems to be duplicated here as well.

The position of the comments area is also important from another perspective:
Should they be before or after the sidebar on small screens? I can not find a design for the mobile version.
I would assume they should be before the sidebar, but this design decision is not up to me.

2024-09-16 06:54 UTC, up1512001 commented
@carolinan for `Right-aligned single post`, moved comments inside the right column so that it will be aligned with content.

2024-09-16 07:04 UTC, carolinan commented
News blog: The positioning is still not correct, the comment area doesn't align with the rest.
<img width="538" alt="The comments area on the news blog single post is further left than next and previous post navigation" src="https://github.com/user-attachments/assets/0a6fa6f1-5ad9-48cb-b5a3-71a3926f6dad">

2024-09-16 11:48 UTC, up1512001 commented
@carolinan fix news blog alignment issue.

https://github.com/user-attachments/assets/e9bbbd01-c41a-469d-acc7-0b7e52cb702e

2024-09-20 13:47 UTC, juanfra commented on patterns/vertical-header-right-aligned-post-template.php
> +			</div>
```suggestion
		<div class="wp-block-group alignwide">	
			<!-- wp:pattern {"slug":"twentytwentyfive/comments"} /-->
		</div>
```

2024-09-20 13:49 UTC, juanfra commented on patterns/news-blog-single-post-with-sidebar-template.php
> +<!-- /wp:group -->
```suggestion
	<!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
	<div class="wp-block-group alignwide" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0">
		<!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"layout":{"type":"constrained"}} -->
		<div class="wp-block-group" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0">
			<!-- wp:pattern {"slug":"twentytwentyfive/comments"} /-->
		</div>
		<!-- /wp:group -->
	</div>
	<!-- /wp:group -->
</div>
<!-- /wp:group -->
```

2024-09-20 14:22 UTC, juanfra requested changes
Thanks for your persistence on this @up1512001! 

There are some that are working well:

✔️ Photo blog single post
✔️ Text-only blog, single post
✔️ Post with left aligned content
✔️ Offset post without featured image

There are two that need improvement

**✖️News blog single post with sidebar**

It's still not aligned with the content. It looks like by wrapping in columns (instead of row) and having a first column with 5% width, that should be solved.

https://github.com/user-attachments/assets/657acc70-3e74-43d2-a428-1e40e3aee6ac

**✖️Right aligned single post**

The comments section is not aligned with the content. It looks like there's some inherited padding that could be affecting that. I'd encourage you to revisit that and check it so that the comments section is aligned with the content.

https://github.com/user-attachments/assets/4b35d4ce-1427-48c2-b8a4-d4804d936ac0

2024-09-22 10:05 UTC, up1512001 commented
@juanfra updated `News blog single post with sidebar` & `Right aligned single post` template as per your suggestion.

2024-09-23 12:33 UTC, juanfra reviewed
Thank you for your persistence @up1512001 - We're almost there!

✔️ **Right aligned single post** - looks good

✖️**News blog single post with sidebar**

We need to adjust a bit the alignment between the content and the comments. It's looking way better now, but they're still not fully aligned. 

https://github.com/user-attachments/assets/2c9d8996-7c7f-4a67-b68d-435752529418

We may want to experiment with the columns, to match a bit what's in the group of the content. And also consider the content alignment of the group that's containing the comments section.

2024-09-23 13:45 UTC, up1512001 commented
@juanfra fixed the alignment issue for `News blog single post with sidebar` also.

https://github.com/user-attachments/assets/fbc2f01e-d2f7-4974-aa85-03e0f0350f1b

I have one doubt should we keep the comment section width the same as the content section width like below or above is fine?


https://github.com/user-attachments/assets/7da615a9-edc9-4669-be7e-dfc98ef4c32d

2024-09-23 14:47 UTC, juanfra commented
Thank you so much @up1512001 

> I have one doubt should we keep the comment section width the same as the content section width like below or above is fine?

Yes, it looks like that in [the design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=6338-2807&t=8sP17K84EIYuEwIV-1).

<img width="972" alt="Screenshot 2024-09-23 at 16 44 50" src="https://github.com/user-attachments/assets/4f82673a-4385-4684-a36e-22bda977e491">

2024-09-23 15:04 UTC, up1512001 commented
@juanfra updated as per design.

2024-09-23 15:20 UTC, juanfra commented on patterns/news-blog-single-post-with-sidebar-template.php
> +					<!-- wp:pattern {"slug":"twentytwentyfive/comments"} /-->
```suggestion
				<!-- wp:pattern {"slug":"twentytwentyfive/comments"} /-->
```

2024-09-23 15:21 UTC, juanfra approved these changes
Thank you so much @up1512001 - Great work 🏅

2024-09-23 15:21 UTC, merged