Try: Escape apostrophe in translation functions.
WordPress/twentytwentyfive pull request #537
Opened 2024-10-09 16:33 UTC by juanfra

**Description**

Replacing `&rsquo;` for an escaped apostrophe (`\'`) in translatable texts.

**Screenshots**

- N/A

**Testing Instructions**

1. Create a page.
2. Insert all the patterns modified in this PR.
3. Confirm the texts are looking as they were before.

2024-10-10 01:48 UTC, carolinan commented
Why, what is the benefit of this change?

2024-10-10 07:54 UTC, juanfra commented
> Why, what is the benefit of this change?

From my experience working with translations, I see that many translators are not technical and don't know about these entities. The benefit would be that it'll be easier for translators to do their work.

I believe historically, in core (and other products I've been involved with), the tendency is to use apostrophes rather than entities.

2024-10-10 07:58 UTC, carolinan commented
That sounds very reasonable to me.

It does not match how these symbols have been managed in the previous bundled themes.
I would like to ask @SergeyBiryukov but he is on vacation until next week.

2024-10-10 08:53 UTC, carolinan commented
I also recognize that on trunk there seems to be a mix of slashes and entities which was not intended :)

2024-10-15 18:54 UTC, SergeyBiryukov requested changes
Thanks for the PR! I would say these are fine to replace, and I see that some of the previous bundled themes already use the actual double quote characters instead of entities.

However, entities are generally used for better typography, so instead of the escaped apostrophe character, I would suggest using an actual single quote, which would not need escaping and also has a precedent in the previous bundled themes.

Left some suggestions, hope this helps 🙂

2024-10-15 18:54 UTC, SergeyBiryukov commented on patterns/banner-about-book.php
> +			<p class="has-medium-font-size"><?php echo esc_html_x( 'This exquisite compilation showcases a diverse array of photographs that capture the essence of different eras and cultures, reflecting the
```suggestion
			<p class="has-medium-font-size"><?php echo esc_html_x( 'This exquisite compilation showcases a diverse array of photographs that capture the essence of different eras and cultures, reflecting the unique styles and perspectives of each artist. Fleckenstein’s evocative imagery, Strand’s groundbreaking modernist approach, and Kōno’s meticulous documentation of Japanese life come together in a harmonious blend that celebrates the art of photography. Each image in “The Stories Book” is accompanied by insightful commentary, providing historical context and revealing the stories behind the photographs. This collection is not only a visual feast but also a tribute to the power of photography to preserve and narrate the multifaceted experiences of humanity.', 'Pattern placeholder text.', 'twentytwentyfive' ); ?></p>
```

2024-10-15 18:54 UTC, SergeyBiryukov commented on patterns/banner-poster.php
> +				<h2 class="wp-block-heading alignwide has-text-align-left has-xx-large-font-size" style="font-style:normal;font-weight:300;line-height:0.9"><?php esc_html_e( 'Let\'s hear them.', 'twentytwentyfiv
```suggestion
				<h2 class="wp-block-heading alignwide has-text-align-left has-xx-large-font-size" style="font-style:normal;font-weight:300;line-height:0.9"><?php esc_html_e( 'Let’s hear them.', 'twentytwentyfive' ); ?></h2>
```

2024-10-15 18:54 UTC, SergeyBiryukov commented on patterns/event-schedule.php
> +									<h4 class="wp-block-heading"><a href="#"><?php esc_html_e( 'Things you didn\'t know about the deep ocean', 'twentytwentyfive' ); ?></a></h4>
```suggestion
									<h4 class="wp-block-heading"><a href="#"><?php esc_html_e( 'Things you didn’t know about the deep ocean', 'twentytwentyfive' ); ?></a></h4>
```

2024-10-15 18:54 UTC, SergeyBiryukov commented on patterns/page-cv-bio.php
> +					<p class="is-style-text-subtitle"><?php echo esc_html_x( 'My name is Nora Winslow Keene, and I\'m a committed public interest attorney. Living in Denver, Colorado, I\'ve spent years championing
```suggestion
					<p class="is-style-text-subtitle"><?php echo esc_html_x( 'My name is Nora Winslow Keene, and I’m a committed public interest attorney. Living in Denver, Colorado, I’ve spent years championing the rights of underrepresented workers. A graduate of Stanford University, I played a key role in securing critical protections for agricultural laborers, ensuring better wages and access to healthcare. My work has focused on advocating for environmental justice and improving the quality of life for rural communities. Every case I take on is driven by the belief that everyone deserves dignity and fair treatment in the workplace.', 'Pattern placeholder text.', 'twentytwentyfive' ); ?></p>
```

2024-10-15 18:54 UTC, SergeyBiryukov commented on patterns/page-link-in-bio-wide-margins.php
> +				<p><?php echo esc_html_x( 'I\'m Nora, a dedicated public interest attorney based in Denver. I\'m a graduate of Stanford University.', 'Pattern placeholder text.', 'twentytwentyfive' ); ?></p>
```suggestion
				<p><?php echo esc_html_x( 'I’m Nora, a dedicated public interest attorney based in Denver. I’m a graduate of Stanford University.', 'Pattern placeholder text.', 'twentytwentyfive' ); ?></p>
```

2024-10-15 18:54 UTC, SergeyBiryukov commented on patterns/page-link-in-bio-with-tight-margins.php
> +				<p class="has-text-align-left has-x-large-font-size" style="line-height:1.2"><?php esc_html_e( 'I\'m Asahachi Kōno, a Japanese photographer, a member of Los Angeles\'s Japanese Camera Pictorialis
```suggestion
				<p class="has-text-align-left has-x-large-font-size" style="line-height:1.2"><?php esc_html_e( 'I’m Asahachi Kōno, a Japanese photographer, a member of Los Angeles’ Japanese Camera Pictorialists of California. Before returning to Japan, I worked as a photo retoucher.', 'twentytwentyfive' ); ?></p>
```

2024-10-16 08:35 UTC, juanfra commented
Thank you both!

2024-10-16 08:36 UTC, juanfra commented on patterns/page-link-in-bio-with-tight-margins.php
> +				<p class="has-text-align-left has-x-large-font-size" style="line-height:1.2"><?php esc_html_e( 'I’m Asahachi Kōno, a Japanese photographer, a member of Los Angeles’ Japanese Camera Pictorialists
```suggestion
				<p class="has-text-align-left has-x-large-font-size" style="line-height:1.2"><?php esc_html_e( 'I’m Asahachi Kōno, a Japanese photographer, a member of Los Angeles’s Japanese Camera Pictorialists of California. Before returning to Japan, I worked as a photo retoucher.', 'twentytwentyfive' ); ?></p>
```

2024-10-16 08:38 UTC, merged